#!/usr/bin/env bash
# Vendor the simplecore bundle into every simple* plugin beside this directory.
#
#   ./vendor.sh              vendor into every sibling simple* plugin
#   ./vendor.sh simplegit    vendor into the named plugins only
#   ./vendor.sh --check      report drift, write nothing, exit 1 if any
#
# Set SIMPLECORE_SUITE when the plugins are not checked out beside this
# directory.
#
# Each plugin is its own git repository and must stay independently
# installable, so the bundle is copied in rather than shared by reference.
# The copies are then pinned by a per-plugin .simplecore.manifest, which
# `make core-verify` checks on every build — that is what makes the drift
# visible instead of silent.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The plugins are normally checked out beside this directory.  They need not be:
# this is its own repository and can be cloned anywhere, so SIMPLECORE_SUITE
# names the directory holding the plugins when it is not the parent.
suite="${SIMPLECORE_SUITE:-$(dirname "$here")}"
if [ ! -d "$suite" ]; then
	echo "vendor.sh: no such directory: $suite" >&2
	echo "       Set SIMPLECORE_SUITE to the directory holding the simple* plugins." >&2
	exit 1
fi
suite="$(cd "$suite" && pwd)"

check_only=0
targets=()
for arg in "$@"; do
	case "$arg" in
	--check) check_only=1 ;;
	-*) echo "vendor.sh: unknown option $arg" >&2; exit 2 ;;
	*) targets+=("$arg") ;;
	esac
done

# With no arguments, discover the suite.  A bare simple* glob is not enough:
# the plugin directory also holds work in progress that has no daemon and no
# repository of its own, and vendoring a supervisor into it would conjure four
# files nobody asked for.  Membership is therefore "is a git repository that
# already carries the bundle" — explicit names still work for onboarding a new
# plugin.
if [ ${#targets[@]} -eq 0 ]; then
	for d in "$suite"/simple*/; do
		[ -d "$d/.git" ] || continue
		[ -f "$d/.simplecore.manifest" ] || continue
		targets+=("$(basename "$d")")
	done
	[ ${#targets[@]} -gt 0 ] || { echo "vendor.sh: no vendored plugins found beside $here" >&2; exit 1; }
fi

version="$(awk '$1 == "VERSION" { print $2 }' "$here/MANIFEST")"
[ -n "$version" ] || { echo "vendor.sh: MANIFEST has no VERSION" >&2; exit 1; }

# Emit "<src> <dst> <mode>" for each record that applies to this plugin, with
# @PLUGIN@ already resolved and any SKIP entries for it filtered out.
records() {
	local plug=$1
	awk -v plug="$plug" '
		/^[[:space:]]*(#|$)/ { next }
		$1 == "VERSION" { next }
		$1 == "SKIP" { if ($2 == plug) skip[$3] = 1; next }
		{ rec[NR] = $1 " " $2 " " $3 }
		END {
			for (n = 1; n <= NR; n++) {
				if (!(n in rec)) continue
				split(rec[n], f, " ")
				if (f[1] in skip) continue
				gsub(/@PLUGIN@/, plug, f[2])
				print f[1], f[2], f[3]
			}
		}
	' "$here/MANIFEST"
}

# Render a source file as it should appear inside the given plugin.
render() {
	local src=$1 mode=$2 plug=$3
	case "$mode" in
	copy) cat "$here/$src" ;;
	template) sed "s/@PLUGIN@/$plug/g" "$here/$src" ;;
	*) echo "vendor.sh: unknown mode '$mode' for $src" >&2; exit 1 ;;
	esac
}

drift=0
for plug in "${targets[@]}"; do
	root="$suite/$plug"
	[ -d "$root" ] || { echo "vendor.sh: no such plugin: $plug" >&2; exit 1; }

	manifest="$root/.simplecore.manifest"
	tmp_manifest="$(mktemp)"
	trap 'rm -f "$tmp_manifest"' EXIT
	{
		echo "# Generated by .simplecore/vendor.sh — do not edit."
		echo "# Verified by \`make core-verify\`; regenerate after changing the bundle."
		echo "version $version"
	} >"$tmp_manifest"

	changed=()
	while read -r src dst mode; do
		[ -n "$src" ] || continue
		tmp="$(mktemp)"
		render "$src" "$mode" "$plug" >"$tmp"
		sum="$(sha256sum <"$tmp" | cut -d' ' -f1)"
		echo "$sum  $dst" >>"$tmp_manifest"

		if [ ! -f "$root/$dst" ] || ! cmp -s "$tmp" "$root/$dst"; then
			changed+=("$dst")
			if [ "$check_only" -eq 0 ]; then
				mkdir -p "$(dirname "$root/$dst")"
				# Preserve the executable bit the source carries.
				cat "$tmp" >"$root/$dst"
				[ -x "$here/$src" ] && chmod +x "$root/$dst"
			fi
		fi
		rm -f "$tmp"
	done < <(records "$plug")

	if [ "$check_only" -eq 1 ]; then
		if [ ${#changed[@]} -ne 0 ] || ! cmp -s "$tmp_manifest" "$manifest"; then
			drift=1
			echo "drift: $plug"
			for f in "${changed[@]}"; do echo "    $f"; done
			cmp -s "$tmp_manifest" "$manifest" || echo "    .simplecore.manifest"
		fi
		rm -f "$tmp_manifest"
	else
		mv "$tmp_manifest" "$manifest"
		if [ ${#changed[@]} -eq 0 ]; then
			echo "$plug: up to date (bundle v$version)"
		else
			echo "$plug: updated ${#changed[@]} file(s) to bundle v$version"
			for f in "${changed[@]}"; do echo "    $f"; done
		fi
	fi
	trap - EXIT
done

exit "$drift"
